export const ActionTypes ={
    SET_PRODUCTS: 'SET_PRODUCTS',
    FAILED_PRODUCTS: 'FAILED_PRODUCTS'
    // SELECTED_PRODUCT: 'SELECTED-PRODUCT',
    // REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    // MEN_PRODUCTS: 'MEN_PRODUCTS',
    // WOMEN_PRODUCTS: 'WOMEN_PRODUCTS',
    // JEWELRY_PRODUCTS:'JEWELRY_PRODUCTS',
    // ELECTRONIC_PRODUCTS: 'ELECTRONIC_PRODUCTS'
};
